remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-assets  # plugin para carregar assets

title: "Página Inicial"
description: "Engenharia e Ciência de Dados"
logo: /assets/images/leticia.png

include:
  - assets/css/custom.css
